`ifndef SYSTEM__SVH
`define SYSTEM__SVH

`define SYSTEM__INPUT_FREQ      "50.0 MHz"
`define SYSTEM__CORE_FREQ       "144.0 MHz"
`define SYSTEM__CORE_FRACTIONAL "false"
`define SYSTEM__VGA_FREQ        "25.175 MHz"
`define SYSTEM__VGA_FRACTIONAL  "true"

`define SYSTEM__POR_TIME 144_000_000

`define SYSTEM__VGA_HORIZONTAL_VISIBLE_AREA 640
`define SYSTEM__VGA_HORIZONTAL_FRONT_PORCH  16
`define SYSTEM__VGA_HORIZONTAL_SYNC_PULSE   96
`define SYSTEM__VGA_HORIZONTAL_BACK_PORCH   48
`define SYSTEM__VGA_VERTICAL_VISIBLE_AREA   480
`define SYSTEM__VGA_VERTICAL_FRONT_PORCH    10
`define SYSTEM__VGA_VERTICAL_SYNC_PULSE     2
`define SYSTEM__VGA_VERTICAL_BACK_PORCH     33

`endif  //SYSTEM__SVH
