`ifndef SYSTEM__SVH
`define SYSTEM__SVH

// Power and clock parameters

`define SYSTEM__INPUT_FREQ      "50.0 MHz"
`define SYSTEM__CORE_FREQ       "144.0 MHz"
`define SYSTEM__CORE_FRACTIONAL "false"
`define SYSTEM__VGA_FREQ        "25.175 MHz"
`define SYSTEM__VGA_FRACTIONAL  "true"

`define SYSTEM__POR_TIME 144_000_000

// VGA parameters

`define SYSTEM__VGA_HORIZONTAL_VISIBLE_AREA 640
`define SYSTEM__VGA_HORIZONTAL_FRONT_PORCH  16
`define SYSTEM__VGA_HORIZONTAL_SYNC_PULSE   96
`define SYSTEM__VGA_HORIZONTAL_BACK_PORCH   48
`define SYSTEM__VGA_VERTICAL_VISIBLE_AREA   480
`define SYSTEM__VGA_VERTICAL_FRONT_PORCH    10
`define SYSTEM__VGA_VERTICAL_SYNC_PULSE     2
`define SYSTEM__VGA_VERTICAL_BACK_PORCH     33

// Memory parameters

`define SYSTEM__MEM_DWIDTH      512
`define SYSTEM__MEM_DWIDTH_CORE 32
`define SYSTEM__MEM_AWIDTH      32
`define SYSTEM__MEM_BSIZE       8

`define SYSTEM__MEM_SM0_BASE    32'h0000_0000
`define SYSTEM__MEM_SM1_BASE    32'h0008_0000
`define SYSTEM__MEM_SMC_BASE    32'h0010_0000

`define SYSTEM__MEM_IMEM_BASE   32'h0000_0000
`define SYSTEM__MEM_DMEM_BASE   32'h0002_0000
`define SYSTEM__MEM_PERIPH_BASE 32'h0004_0000

`define SYSTEM__MEM_IMEM_SIZE   (2048 * 16 * 4)
`define SYSTEM__MEM_DMEM_SIZE   (2048 * 16 * 4)
`define SYSTEM__MEM_PERIPH_SIZE (2048 * 16 * 4 * 2)

`define SYSTEM__MEM_SM0_IMEM    `SYSTEM__MEM_SM0_BASE + `SYSTEM__MEM_IMEM_BASE
`define SYSTEM__MEM_SM0_DMEM    `SYSTEM__MEM_SM0_BASE + `SYSTEM__MEM_DMEM_BASE
`define SYSTEM__MEM_SM0_PERIPH  `SYSTEM__MEM_SM0_BASE + `SYSTEM__MEM_PERIPH_BASE
`define SYSTEM__MEM_SM1_IMEM    `SYSTEM__MEM_SM1_BASE + `SYSTEM__MEM_IMEM_BASE
`define SYSTEM__MEM_SM1_DMEM    `SYSTEM__MEM_SM1_BASE + `SYSTEM__MEM_DMEM_BASE
`define SYSTEM__MEM_SM1_PERIPH  `SYSTEM__MEM_SM1_BASE + `SYSTEM__MEM_PERIPH_BASE
`define SYSTEM__MEM_SMC         `SYSTEM__MEM_SMC_BASE

// Serial parameters

`define SYSTEM__SERIAL_FIFO_DEPTH     4
`define SYSTEM__SERIAL_NSPI_WIDTH     32
`define SYSTEM__SERIAL_NSPI_INSTANCES 4

`endif //SYSTEM__SVH
